security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Payutc\OnyxBundle\Entity\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        local:
            entity:
                class: Payutc\OnyxBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern: ^/admin/login$
            anonymous: ~

        admin_area:
            pattern: ^/admin
            provider: local
            form_login:
                login_path: payutc_admin_login
                check_path: payutc_admin_login_check
                default_target_path: payutc_admin_homepage
                post_only: true
            logout:
                path: payutc_admin_logout
                target: /
                invalidate_session: false
            casauth: true

        front_login:
            pattern: ^/login$
            anonymous: ~

        front_area:
            pattern: ^/
            provider: local
            anonymous: ~
            form_login:
                login_path: pay_utc_onyx_login_page
                check_path: pay_utc_onyx_login_check_page
                post_only: true
                remember_me: true
            logout:
                path: pay_utc_onyx_logout_page
                target: /
                invalidate_session: false
            remember_me:
                key: payutc_s3cre3t
                name: payutc-user-remember
                lifetime: 86400
                always_remember_me: true
                remember_me_parameter: _remember_me
            casauth: true

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
