parameters:
    mailer:
        from:
            name: Billeterie UTC
            email: noreply@utc.fr
        subjects:
            cas_authentication: Billeterie UTC - Inscription
            registration: Billeterie UTC - Inscription
    cas:
        base_url: https://cas.utc.fr/cas/
    ginger:
        name: fauxginger
        url: http://localhost/faux-ginger/index.php/v1/